twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        admin_host: '%admin_host%'
        main_host: '%main_host%'
        app_scheme: '%app_scheme%'

when@test:
    twig:
        strict_variables: true
