controllers_api:
    resource: ../src/Infrastructure/Ui/Controller/Api/
    type: attribute

controllers_home:
    resource: ../src/Infrastructure/Ui/Controller/Home/
    type: attribute

admin:
    resource: ../src/Infrastructure/Ui/Controller/Admin/
    type: attribute
    host: '%admin_host%'
